Clear-Host
Write-Host "=========================================================" -ForegroundColor Cyan
Write-Host "         HELIUS BLOCKCHAIN ROUTING ENGINE SETUP          " -ForegroundColor Yellow
Write-Host "=========================================================" -ForegroundColor Cyan
Write-Host ""

# Ask for the API KEY only. The RPC URL is always derived from the key in the
# canonical form  https://mainnet.helius-rpc.com/?api-key=<KEY>  so a malformed
# pasted URL can never break the app again.
$InputKey = Read-Host -Prompt "--> Paste Your Helius API Key (the UUID, not a full URL)"

# Strip whitespace AND any stray single/double quotes the user may have pasted.
$InputKey = $InputKey.Trim().Trim('"').Trim("'").Trim()

if (-not $InputKey) {
    Write-Warning "`n[X] Error: API key cannot be blank. Setup aborted."
    return
}

# If the user pasted a full URL, pull the api-key value out of it.
if ($InputKey -match "api-key=([0-9a-fA-F-]+)") {
    $InputKey = $Matches[1]
    Write-Host "[i] Extracted key from the URL you pasted." -ForegroundColor DarkGray
}

$RpcUrl = "https://mainnet.helius-rpc.com/?api-key=$InputKey"

# --- Live handshake test (done correctly: real getHealth against the real URL) ---
Write-Host "`n[...] Testing live connection to Helius..." -ForegroundColor Cyan
$body = @{ jsonrpc = "2.0"; id = 1; method = "getHealth" } | ConvertTo-Json
$ok = $false
try {
    $resp = Invoke-RestMethod -Uri $RpcUrl -Method Post -Body $body -ContentType "application/json" -TimeoutSec 20
    if ($resp.result -eq "ok") {
        $ok = $true
        Write-Host "[OK] Helius handshake succeeded (result = ok)." -ForegroundColor Green
    } else {
        Write-Warning "[!] Unexpected response: $($resp | ConvertTo-Json -Compress)"
    }
} catch {
    Write-Warning "[X] Handshake FAILED: $($_.Exception.Message)"
    Write-Host "    The key may be invalid, throttled, or out of credits." -ForegroundColor Yellow
}

if (-not $ok) {
    $go = Read-Host "`nSave credentials anyway? (y/N)"
    if ($go -notmatch '^[Yy]') { Write-Warning "Aborted. Nothing was written."; return }
}

# Write a clean credentials.py (no stray quotes; app.py loads this file directly).
$ConfigContent = @(
    "# Auto-generated by configure_env.ps1 - do not add quotes manually.",
    "HELIUS_API_KEY = `"$InputKey`"",
    "HELIUS_RPC_URL = `"$RpcUrl`""
)
$target = "C:\Users\GEDZI\Desktop\PNL 2\credentials.py"
$ConfigContent | Out-File -FilePath $target -Encoding utf8 -Force

Write-Host "`n[OK] Saved to credentials.py" -ForegroundColor Green
Write-Host "     Key : $($InputKey.Substring(0,4))...$($InputKey.Substring($InputKey.Length-4))" -ForegroundColor DarkGray
Write-Host "     URL : https://mainnet.helius-rpc.com/?api-key=****" -ForegroundColor DarkGray
Write-Host "`nYou can now launch the dashboard with pnl_two.cmd" -ForegroundColor Cyan
